### ISSUE TITLE
deps/build.jl fails on Ubuntu/Debian using version 0.4.0-dev+4850

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/RCall.jl#55] opened 2015-05-15 18:28 UTC
I haven't dug into exactly why this is failing on v"0.4.0-dev" and not on version 0.3.8 but
```
~/.julia/v0.4/RCall/deps$ julia -e 'println(versioninfo()); include("build.jl")'
Julia Version 0.3.8
Commit 79599ad (2015-04-30 23:40 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD Athlon(tm) II X4 635 Processor
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
nothing
bates@thin40:~/.julia/v0.4/RCall/deps$ julia4 -e 'println(versioninfo()); include("build.jl")'
Julia Version 0.4.0-dev+4850
Commit c260ea9* (2015-05-15 15:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD Athlon(tm) II X4 635 Processor
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY BARCELONA)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.0
nothing
ERROR: LoadError: Unable to locate libR.so
Try setting R_HOME, and re-run Pkg.build("RCall").
 in error at ./error.jl:21
 in anonymous at ./no file:44
 in include at ./boot.jl:252
 in include_from_node1 at ./loading.jl:134
 in process_options at ./client.jl:288
 in _start at ./client.jl:409
while loading /home/bates/.julia/v0.4/RCall/deps/build.jl, in expression starting on line 3
```

**Comment by simonbyrne** [comment] 2015-05-16 10:56
I did recently rearrange the `deps/build.jl` code to get it to work on Windows, so I may have broken something, but I can't reproduce this on either OS X or Linux.

**Comment by dmbates** [comment] 2015-05-16 15:32
I should have mentioned that I am using the Ubuntu package r-base which puts the Rscript executable into /usr/bin and most of the rest in /usr/lib/R/.  I'll trace it through and find where it is failing.

**Comment by dmbates** [comment] 2015-05-20 16:08
For some reason the `dlopen_e` call in `RCall/deps/build.jl` is failing even though the files exists and apparently has the correct type and contents.  
```
julia> versioninfo()
Julia Version 0.4.0-dev+4911
Commit 4c2f908* (2015-05-20 14:25 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD Athlon(tm) II X4 635 Processor
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY BARCELONA)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.6.0

julia> Rlib
"/usr/lib/R/lib/libR.so"

shell> file $Rlib
/usr/lib/R/lib/libR.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=aadb069cdbf838d8d431bbc44e9270c7960161af, stripped

julia> Libdl.dlopen(Rlib)
ERROR: could not load module /usr/lib/R/lib/libR.so: no error
 in dlopen at ./libdl.jl:35
```

I'm a bit curious as to why the error condition is "no error".

**Comment by simonbyrne** [comment] 2015-05-20 16:25
That's odd. Does adding a `const` in front of the definition of `Rlib` fix it?

**Comment by dmbates** [comment] 2015-05-20 16:39
Adding `const` to the definition of `Rlib` didn't help.  I also tried putting all the definitions from `Renv` into `ENV` but that didn't work either.  Should we pass this up the chain and create an issue in `JuliaLang/julia`?

**Comment by simonbyrne** [comment] 2015-05-20 16:40
Yes, I think that's a good idea.

**Comment by dmbates** [comment] 2015-06-15 12:04
I am beginning to suspect that this is triggered by the linkage to the BLAS/LAPACK library.  I find that if I use different BLAS/LAPACK versions, say OpenBLAS for R and MKL for Julia, then I can start RCall.  Except that now there is another problem with RCall on under v0.4, which I will create another issue for.

**Comment by simonbyrne** [comment] 2015-08-24 15:38
@dmbates Did you ever resolve this?

**Comment by dmbates** [comment] 2015-08-24 16:19
@simonbyrne In the sense of "don't do that", yes.  Trying to link to different versions of MKL on the Julia side and on the R side is asking for problems.

**Comment by simonbyrne** [comment] 2015-08-24 16:25
Okay, I'll close this. If you think others are likely to get bitten by, maybe add some lines to [doc/Installation.md](https://github.com/JuliaStats/RCall.jl/blob/master/doc/Installation.md).

**Closed** 2015-08-24 16:26 UTC
