### ISSUE TITLE
using RCall Fails on Mac OSX

### ISSUE THREAD

**Issue by joshualeond** [JuliaStats/RCall.jl#131] opened 2016-07-02 20:18 UTC
I've been using RCall on Windows with no problem but I've attempted installing the RCall package on Mac OSX and always get this error after `using RCall`:

>ERROR: InitError: UndefVarError: unsafe_wrap not defined
 in getindex at /Users/joshualeond/.julia/v0.4/RCall/src/methods.jl:102
 in rgui_init at /Users/joshualeond/.julia/v0.4/RCall/src/eventloop.jl:75
 in __init__ at /Users/joshualeond/.julia/v0.4/RCall/src/setup.jl:195
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at /usr/local/Cellar/julia/0.4.6_1/lib/julia/sys.dylib
 in require at /usr/local/Cellar/julia/0.4.6_1/lib/julia/sys.dylib
during initialization of module RCall

I've been browsing issues for `unsafe_wrap` but can't find a similar problem.  I'm using the following version of RCall:
> RCall 0.4.1+ master

Perhaps it's an issue with my R installation.  RCall does find the path to my R installation but the failure being around rgui_init may deal with my install.

**Comment by randy3k** [comment] 2016-07-02 20:32
Could you upgrade RCall to v0.5.0 and try again?

**Comment by joshualeond** [comment] 2016-07-02 21:09
Yes, that was it.  I assumed I was at the latest version because I checked out the master repo.  I think my DataFrames package needed to be updated as well.  

Other than this I did have an error when trying to run anything in the R REPL mode:
>Assertion failed: (ctx->gensym_assigned.at(idx)), function emit_expr, file codegen.cpp, line 3155.
  
That problem was related to my Julia installation being through Homebrew.  After I installed the julia .dmg from the Julia site it all works great. Thanks.

**Comment by randy3k** [comment] 2016-07-03 09:52
@joshualeond 

I can reproduce your error with homebrew julia.

**Comment by pochoi** [comment] 2016-07-04 19:48
Is this issue related to this?
https://github.com/JuliaLang/julia/issues/16546

**Comment by randy3k** [comment] 2016-07-06 17:11
@pochoi it seems to be the same issue.

Anyway, I will close this for now.

**Closed** 2016-07-06 17:12 UTC
